modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="duality"
version="1.0.0"
displayName="Duality"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Kpada, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.duality]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



